# Generated by Django 5.1.3 on 2024-12-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='danjovarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
